global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
- job_name: swim-consistent-hashing-monitoring
  honor_labels: true
  static_configs:
  - targets: ['host.docker.internal:8945', 'host.docker.internal:8946', 'host.docker.internal:8947', 'host.docker.internal:8948', 'host.docker.internal:8949']